version: '2'
services:
  node:
    build: .
    volumes:
      -  ~/apps/tbd:/var/www/
      - /var/www/node_modules
    ports:
      - "4040"
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=tdb
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    ports:
      - "3307:3306"
    volumes:
      - ~/apps/tdb_mysql:/var/lib/mysql